#!/bin/sh

logfile="$HOME/.nettestlog"

up="true"
down="true"

while true; do
	ping -c1 8.8.8.8 2>/tmp/errors | grep "64 bytes from " >/dev/null ; rescode=`echo $?`
	cat /tmp/errors 2>/dev/null | tail -1 | grep "Network is unreachable" 2>&1 >/dev/null ; errcode=`echo $?`
	if [[ $errcode -eq 0 ]]; then
		#notify-send -u critical 'ERROR!' 'Network is unrechable!'
		tstamp=`date | tr -d '\n'`
		echo "[-] $tstamp: ERROR! Network is unreachable!" >>$logfile
	else
		if [[ $rescode -ne 0 && "$up" == "true" ]]; then
			#notify-send -u critical 'WHOA!' 'You just lost Internet :O'
			tstamp=`date | tr -d '\n'`
			echo "[-] $tstamp: WHOA! You just lost Internet :O" >>$logfile
			down="true"
			up="false"
		elif [[ $rescode -eq 0 && "$down" == "true" ]]; then
			#notify-send -u normal 'YIPPEE!' 'Internet is back :)'
			tstamp=`date | tr -d '\n'`
			echo "[+] $tstamp: YIPPEE! Internet is back :)" >>$logfile
			up="true"
			down="false"
		fi
	fi
	sleep 10s
done
