#!/bin/sh

# colors: 01:normal 02:white 03:red 04:green 05:yellow 06:blue 07:cyan 08:magenta 09:grey

source $HOME/.functions

dsk() {
	diskinfo
	echo -en "${useddisk}G $useddiskper%"
}

mem() {
	memoryinfo
	echo -en "${actusedmem}M $actusedmemper%"

}

cpu() {
	cpubasicinfo
	echo -en "$cpu"
}

tmp() {
	acpiinfo
	coretmp
	echo -en "${ctmp}C"
}

net() {
	netspeedinfo
	echo -en "${rxdif}K/s ${txdif}K/s"
}

pac() {
	datedpackages
	[ $pac == 0 ] && echo "0" || echo -en "$pac"
}

bat() {
	acpiinfo
	[ "$adapter" == "off-line" ] && echo -en "$battery DC" || echo -en "$battery% AC"
}

vol(){
	speakerstatus
	if [ $mute == "[on]" ]; then
		speakervolume
		echo -e "$vol%"
	else
		echo -e "MUT"
	fi
}

dte() {
	currentdatetime
	echo -en "$dte"
}

echo "DSK $(dsk) | MEM $(mem) | CPU $(cpu) | TMP $(tmp) | NET $(net) | PKG $(pac) | BAT $(bat) | VOL $(vol) | $(dte)"


