#!/bin/sh
# Weather: displays weather forecast in dmenu
# Only for US cities

#Enter city and state below. Replace spaces with "+"
CITY="New+York"
STATE=NY

wget -O /tmp/weather.html 'http://forecast.weather.gov/MapClick.php?e=1&TextType=1&CityName='$CITY'&state='$STATE'&site=BOX&textField1=42.3751&textField2=-72.52' > /dev/null 2>&1

lynx -width 250 -dump /tmp/weather.html | awk '
BEGIN {FS=":"}
/(day|night|Night)/ {
gsub(/^ */,"",$0);
printf "%-20s: %s\n",$1,$2
}
'

